name: dramaProject-CI
on: [ pull_request ]
permissions:
  contents: read
  checks: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Docker
        run: docker compose up -d

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Conduct Tests
        run: ./gradlew test --info

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

      - name: Run Checkstyle
        uses: nikitasavinov/checkstyle-action@master
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-check'
          tool_name: 'reviewdog'
          checkstyle_config: 'config/checkstyle/checkstyle.xml'
          workdir: 'src/main'
          level: warning

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        if: always()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Actions Status Discord
        uses: sarisia/actions-status-discord@v1.11.1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}